In [1]:
import pandas as pd

In [27]:
curve_universe = pd.read_excel('curve_construction_universe_template.xlsx', sheet_name = 'Curve Universe')
curve_universe = curve_universe.dropna(how='all')

In [29]:
curve_universe

,instrument_id,instrument_type,cusip,settlement_date,maturity_date,coupon_rate,coupon_frequency,day_count,face_value,clean_price,accrued_interest,dirty_price,notes
0,UST-BILL-1M,bill,912797AA1,2026-07-12,2026-08-12,0.0000,0,ACT/360,100,99.63,0,99.63,Short bill proxy; zero coupon.
1,UST-BILL-3M,bill,912797AB9,2026-07-12,2026-10-12,0.0000,0,ACT/360,100,98.91,0,98.91,Bill used for front-end discount factor.
2,UST-BILL-6M,bill,912797AC7,2026-07-12,2027-01-12,0.0000,0,ACT/360,100,97.86,0,97.86,Bill used for 6M discount factor.
3,UST-NOTE-1Y,note,91282CAA1,2026-07-12,2027-07-12,0.0390,2,ACT/ACT,100,99.78,0,99.78,Short coupon note.
4,UST-NOTE-2Y,note,91282CAB9,2026-07-12,2028-07-12,0.0400,2,ACT/ACT,100,99.74,0,99.74,On-the-run style 2Y note proxy.
5,UST-NOTE-3Y,note,91282CAC7,2026-07-12,2029-07-12,0.0410,2,ACT/ACT,100,99.63,0,99.63,3Y note proxy.
6,UST-NOTE-5Y,note,91282CAD5,2026-07-12,2031-07-12,0.0425,2,ACT/ACT,100,99.35,0,99.35,5Y note proxy.
7,UST-NOTE-7Y,note,91282CAE3,2026-07-12,2033-07-12,0.0440,2,ACT/ACT,100,99.06,0,99.06,7Y note proxy.
8,UST-NOTE-10Y,note,91282CAF0,2026-07-12,2036-07-12,0.0450,2,ACT/ACT,100,98.72,0,98.72,10Y note proxy.
9,UST-BOND-20Y,bond,912810AA1,2026-07-12,2046-07-12,0.0470,2,ACT/ACT,100,97.95,0,97.95,20Y bond proxy.
10,UST-BOND-30Y,bond,912810AB9,2026-07-12,2056-07-12,0.0475,2,ACT/ACT,100,97.41,0,97.41,30Y bond proxy.

In [31]:
curve_universe['maturity_date'] = pd.to_datetime(curve_universe['maturity_date'])
curve_universe['settlement_date'] = pd.to_datetime(curve_universe['settlement_date'])

In [33]:
curve_universe['time_to_maturity'] = (curve_universe['maturity_date'] - curve_universe['settlement_date']).dt.days/365.25

In [35]:
curve_universe

,instrument_id,instrument_type,cusip,settlement_date,maturity_date,coupon_rate,coupon_frequency,day_count,face_value,clean_price,accrued_interest,dirty_price,notes,time_to_maturity
0,UST-BILL-1M,bill,912797AA1,2026-07-12,2026-08-12,0.0000,0,ACT/360,100,99.63,0,99.63,Short bill proxy; zero coupon.,0.084873
1,UST-BILL-3M,bill,912797AB9,2026-07-12,2026-10-12,0.0000,0,ACT/360,100,98.91,0,98.91,Bill used for front-end discount factor.,0.251882
2,UST-BILL-6M,bill,912797AC7,2026-07-12,2027-01-12,0.0000,0,ACT/360,100,97.86,0,97.86,Bill used for 6M discount factor.,0.503765
3,UST-NOTE-1Y,note,91282CAA1,2026-07-12,2027-07-12,0.0390,2,ACT/ACT,100,99.78,0,99.78,Short coupon note.,0.999316
4,UST-NOTE-2Y,note,91282CAB9,2026-07-12,2028-07-12,0.0400,2,ACT/ACT,100,99.74,0,99.74,On-the-run style 2Y note proxy.,2.001369
5,UST-NOTE-3Y,note,91282CAC7,2026-07-12,2029-07-12,0.0410,2,ACT/ACT,100,99.63,0,99.63,3Y note proxy.,3.000684
6,UST-NOTE-5Y,note,91282CAD5,2026-07-12,2031-07-12,0.0425,2,ACT/ACT,100,99.35,0,99.35,5Y note proxy.,4.999316
7,UST-NOTE-7Y,note,91282CAE3,2026-07-12,2033-07-12,0.0440,2,ACT/ACT,100,99.06,0,99.06,7Y note proxy.,7.000684
8,UST-NOTE-10Y,note,91282CAF0,2026-07-12,2036-07-12,0.0450,2,ACT/ACT,100,98.72,0,98.72,10Y note proxy.,10.001369
9,UST-BOND-20Y,bond,912810AA1,2026-07-12,2046-07-12,0.0470,2,ACT/ACT,100,97.95,0,97.95,20Y bond proxy.,20.000000
10,UST-BOND-30Y,bond,912810AB9,2026-07-12,2056-07-12,0.0475,2,ACT/ACT,100,97.41,0,97.41,30Y bond proxy.,30.001369

In [37]:
curve_universe = curve_universe.sort_values(by = 'time_to_maturity')

In [39]:
curve_universe['dirty_price'] = curve_universe['clean_price'] + curve_universe['accrued_interest']

,instrument_id,instrument_type,cusip,settlement_date,maturity_date,coupon_rate,coupon_frequency,day_count,face_value,clean_price,accrued_interest,dirty_price,notes,time_to_maturity
0,UST-BILL-1M,bill,912797AA1,2026-07-12,2026-08-12,0.0000,0,ACT/360,100,99.63,0,99.63,Short bill proxy; zero coupon.,0.084873
1,UST-BILL-3M,bill,912797AB9,2026-07-12,2026-10-12,0.0000,0,ACT/360,100,98.91,0,98.91,Bill used for front-end discount factor.,0.251882
2,UST-BILL-6M,bill,912797AC7,2026-07-12,2027-01-12,0.0000,0,ACT/360,100,97.86,0,97.86,Bill used for 6M discount factor.,0.503765
3,UST-NOTE-1Y,note,91282CAA1,2026-07-12,2027-07-12,0.0390,2,ACT/ACT,100,99.78,0,99.78,Short coupon note.,0.999316
4,UST-NOTE-2Y,note,91282CAB9,2026-07-12,2028-07-12,0.0400,2,ACT/ACT,100,99.74,0,99.74,On-the-run style 2Y note proxy.,2.001369
5,UST-NOTE-3Y,note,91282CAC7,2026-07-12,2029-07-12,0.0410,2,ACT/ACT,100,99.63,0,99.63,3Y note proxy.,3.000684
6,UST-NOTE-5Y,note,91282CAD5,2026-07-12,2031-07-12,0.0425,2,ACT/ACT,100,99.35,0,99.35,5Y note proxy.,4.999316
7,UST-NOTE-7Y,note,91282CAE3,2026-07-12,2033-07-12,0.0440,2,ACT/ACT,100,99.06,0,99.06,7Y note proxy.,7.000684
8,UST-NOTE-10Y,note,91282CAF0,2026-07-12,2036-07-12,0.0450,2,ACT/ACT,100,98.72,0,98.72,10Y note proxy.,10.001369
9,UST-BOND-20Y,bond,912810AA1,2026-07-12,2046-07-12,0.0470,2,ACT/ACT,100,97.95,0,97.95,20Y bond proxy.,20.000000
10,UST-BOND-30Y,bond,912810AB9,2026-07-12,2056-07-12,0.0475,2,ACT/ACT,100,97.41,0,97.41,30Y bond proxy.,30.001369

In [41]:
df = {}

In [ ]:
for _, row in curve_construction_universe.iterrows():
    c = row['coupon_rate']
    T = row['time_to_maturity']
    start_date = row['settlement_date']
    end_date = row['maturity_date']
    dirty_price = row['dirty_price']
    face_value = row['face_value']
    freq = row['coupon_freq']
    cf_period = 12//freq
    dc_conv = row['day_count']
    
    if c == 0:
        df[T] = dirty_price/face_value
        
    else:
        npv_cf = 0
        final_cf = 0
        date = end_date
        while date > start_date:
            if date == end_date:
                final_cf = face_value*(1 + c/freq)
                
            else:
                yf = year_fraction(start_date, end_date, dc_conv)
                cf = face_value*c/freq
                npv_cf += cf*DF(yf, df)
                date -= pd.DateOffset(months=cf_period)

        df[T] = (dirty_price - npv_cf)/final_cf

In [43]:
def year_fraction(start_date, end_date, dc_conv):
    days = (end_date - start_date).days
    if dc_conv == "ACT/365.25":
        return days/365.25
    if dc_conv == "ACT/365":
        return days/365
    if dc_conv == "ACT/360":
        return days/360
    elif dc_conv == "ACT/ACT":
        if days == 0:
            return 0.0

        total = 0.0
        current = start_date

        while current < end_date:
            next_year = pd.Timestamp(
                year=current.year + 1,
                month=1,
                day=1
            )

            period_end = min(end_date, next_year)
            days_in_year = 366 if current.is_leap_year else 365

            total += (period_end - current).days / days_in_year
            current = period_end

        return total
    else:
        raise ValueError("day_count must be ACT/ACT, ACT/365.25, ACT/365, or ACT/360")

In [45]:
def DF(t, df):
    if t in df.keys():
        return df[t]
    t_vals = sorted(df.keys())
    if t < t_vals[0]:
        return df[t_vals[0]]
    elif t > t_vals[-1]:
        return df[t_vals[-1]]
    for idx in range(len(df) - 1):
        t1 = t_vals[idx] 
        t2 = t_vals[idx + 1]
        if t1 < t and t2 > t:
            d = log_interpolate(t, df[t1], df[t2], t1, t2)
            return d

In [49]:
dct = {'a': 'bdiuweb', 'b':'bdiuwebiuwe', 'c':'wbuwvbfuwehb'}
sorted(dct.keys())

['a', 'b', 'c']

In [ ]:
def log_interpolate(t, d1, d2, t1, t2):
    log_d1 = math.log(d1)
    log_d2 = math.log(d2)
    log_d = log_d1 + ((log_d2 - log_d1)/(t2 - t1))*(t - t1)
    d = math.exp(log_d)
    return d

In [ ]:
import pandas as pd
import math


def year_fraction(start_date, end_date, dc_conv):
    days = (end_date - start_date).days
    if dc_conv == "ACT/365.25":
        return days/365.25
    if dc_conv == "ACT/365":
        return days/365
    if dc_conv == "ACT/360":
        return days/360
    elif dc_conv == "ACT/ACT":
        if days == 0:
            return 0.0

        total = 0.0
        current = start_date

        while current < end_date:
            next_year = pd.Timestamp(
                year=current.year + 1,
                month=1,
                day=1
            )

            period_end = min(end_date, next_year)
            days_in_year = 366 if current.is_leap_year else 365

            total += (period_end - current).days / days_in_year
            current = period_end

        return total
    else:
        raise ValueError("day_count must be ACT/ACT, ACT/365.25, ACT/365, or ACT/360")


def DF(t, df):
    if t in df.keys():
        return df[t]
    t_vals = sorted(df.keys())
    if t < t_vals[0]:
        return df[t_vals[0]]
    elif t > t_vals[-1]:
        return df[t_vals[-1]]
    for idx in range(len(df) - 1):
        t1 = t_vals[idx] 
        t2 = t_vals[idx + 1]
        if t1 < t and t2 > t:
            d = log_interpolate(t, df[t1], df[t2], t1, t2)
            return d

def log_interpolate(t, d1, d2, t1, t2):
    log_d1 = math.log(d1)
    log_d2 = math.log(d2)
    log_d = log_d1 + ((log_d2 - log_d1)/(t2 - t1))*(t - t1)
    d = math.exp(log_d)
    return d
    


curve_universe = pd.read_excel('curve_construction_universe_template.xlsx', sheet_name = 'Curve Universe')
curve_universe = curve_universe.dropna(how='all')

curve_universe['maturity_date'] = pd.to_datetime(curve_universe['maturity_date'])
curve_universe['settlement_date'] = pd.to_datetime(curve_universe['settlement_date'])

curve_universe['time_to_maturity'] = (curve_universe['maturity_date'] - curve_universe['settlement_date']).dt.days/365.25

curve_universe = curve_universe.sort_values(by = 'time_to_maturity')
curve_universe['dirty_price'] = curve_universe['clean_price'] + curve_universe['accrued_interest']

df = {}

for _, row in curve_universe.iterrows():
    c = row['coupon_rate']
    T = row['time_to_maturity']
    start_date = row['settlement_date']
    end_date = row['maturity_date']
    dirty_price = row['dirty_price']
    face_value = row['face_value']
    freq = int(row['coupon_frequency'])
    dc_conv = row['day_count']
    
    if freq == 0:
        df[T] = dirty_price/face_value
        
    else:
        cf_period = 12//freq
        npv_cf = 0
        final_cf = 0
        date = end_date
        while date > start_date:
            if date == end_date:
                final_cf = face_value*(1 + c/freq)
                
            else:
                yf = year_fraction(start_date, date, dc_conv)
                cf = face_value*c/freq
                npv_cf += cf*DF(yf, df)
                
            date -= pd.DateOffset(months=cf_period)

        df[T] = (dirty_price - npv_cf)/final_cf